#ifndef POKEPLATINUM_CONSTANTS_FORMS_H
#define POKEPLATINUM_CONSTANTS_FORMS_H

#include "constants/species.h"

#define MOVESET_FORM_DEOXYS_ATTACK    NATIONAL_DEX_COUNT + 1
#define MOVESET_FORM_DEOXYS_DEFENSE   NATIONAL_DEX_COUNT + 2
#define MOVESET_FORM_DEOXYS_SPEED     NATIONAL_DEX_COUNT + 3
#define MOVESET_FORM_WORMADAM_SANDY   NATIONAL_DEX_COUNT + 4
#define MOVESET_FORM_WORMADAM_TRASH   NATIONAL_DEX_COUNT + 5
#define MOVESET_FORM_GIRATINA_ORIGIN  NATIONAL_DEX_COUNT + 6
#define MOVESET_FORM_SHAYMIN_SKY      NATIONAL_DEX_COUNT + 7
#define MOVESET_FORM_ROTOM_HEAT       NATIONAL_DEX_COUNT + 8
#define MOVESET_FORM_ROTOM_WASH       NATIONAL_DEX_COUNT + 9
#define MOVESET_FORM_ROTOM_FROST      NATIONAL_DEX_COUNT + 10
#define MOVESET_FORM_ROTOM_FAN        NATIONAL_DEX_COUNT + 11
#define MOVESET_FORM_ROTOM_MOW        NATIONAL_DEX_COUNT + 12
#define MOVESET_FORM_LUCARIO_MEGA     NATIONAL_DEX_COUNT + 13
#define MOVESET_FORM_LUCARIO_MEGA_Z   NATIONAL_DEX_COUNT + 14
#define MOVESET_FORM_TYRANITAR_MEGA   NATIONAL_DEX_COUNT + 15
#define MOVESET_FORM_VENUSAUR_MEGA    NATIONAL_DEX_COUNT + 16
#define MOVESET_FORM_BLASTOISE_MEGA   NATIONAL_DEX_COUNT + 17
#define MOVESET_FORM_BEEDRILL_MEGA    NATIONAL_DEX_COUNT + 18
#define MOVESET_FORM_PIDGEOT_MEGA     NATIONAL_DEX_COUNT + 19
#define MOVESET_FORM_SLOWBRO_MEGA     NATIONAL_DEX_COUNT + 20
#define MOVESET_FORM_GENGAR_MEGA      NATIONAL_DEX_COUNT + 21
#define MOVESET_FORM_PINSIR_MEGA      NATIONAL_DEX_COUNT + 22
#define MOVESET_FORM_AMPHAROS_MEGA    NATIONAL_DEX_COUNT + 23
#define MOVESET_FORM_STEELIX_MEGA     NATIONAL_DEX_COUNT + 24
#define MOVESET_FORM_SCIZOR_MEGA      NATIONAL_DEX_COUNT + 25
#define MOVESET_FORM_HERACROSS_MEGA   NATIONAL_DEX_COUNT + 26
#define MOVESET_FORM_HOUNDOOM_MEGA    NATIONAL_DEX_COUNT + 27
#define MOVESET_FORM_SCEPTILE_MEGA    NATIONAL_DEX_COUNT + 28
#define MOVESET_FORM_BLAZIKEN_MEGA    NATIONAL_DEX_COUNT + 29
#define MOVESET_FORM_SWAMPERT_MEGA    NATIONAL_DEX_COUNT + 30
#define MOVESET_FORM_SABLEYE_MEGA     NATIONAL_DEX_COUNT + 31
#define MOVESET_FORM_MAWILE_MEGA      NATIONAL_DEX_COUNT + 32
#define MOVESET_FORM_AGGRON_MEGA      NATIONAL_DEX_COUNT + 33
#define MOVESET_FORM_MEDICHAM_MEGA    NATIONAL_DEX_COUNT + 34
#define MOVESET_FORM_MANECTRIC_MEGA   NATIONAL_DEX_COUNT + 35
#define MOVESET_FORM_BANETTE_MEGA     NATIONAL_DEX_COUNT + 36
#define MOVESET_FORM_ALAKAZAM_MEGA    NATIONAL_DEX_COUNT + 37
#define MOVESET_FORM_GYARADOS_MEGA    NATIONAL_DEX_COUNT + 38
#define MOVESET_FORM_ABSOL_MEGA       NATIONAL_DEX_COUNT + 39
#define MOVESET_FORM_ABSOL_MEGA_Z     NATIONAL_DEX_COUNT + 40
#define MOVESET_FORM_GLALIE_MEGA      NATIONAL_DEX_COUNT + 41
#define MOVESET_FORM_SALAMENCE_MEGA   NATIONAL_DEX_COUNT + 42
#define MOVESET_FORM_LOPUNNY_MEGA     NATIONAL_DEX_COUNT + 43
#define MOVESET_FORM_GARCHOMP_MEGA    NATIONAL_DEX_COUNT + 44
#define MOVESET_FORM_ABOMASNOW_MEGA   NATIONAL_DEX_COUNT + 45
#define MOVESET_FORM_GALLADE_MEGA     NATIONAL_DEX_COUNT + 46
#define MOVESET_FORM_GARDEVOIR_MEGA   NATIONAL_DEX_COUNT + 47
#define MOVESET_FORM_ALTARIA_MEGA     NATIONAL_DEX_COUNT + 48
#define MOVESET_FORM_SHARPEDO_MEGA    NATIONAL_DEX_COUNT + 49
#define MOVESET_FORM_DRAGONITE_MEGA   NATIONAL_DEX_COUNT + 50
#define MOVESET_FORM_CLEFABLE_MEGA    NATIONAL_DEX_COUNT + 51
#define MOVESET_FORM_FROSLASS_MEGA    NATIONAL_DEX_COUNT + 52
#define MOVESET_FORM_CHARIZARD_MEGA_Y NATIONAL_DEX_COUNT + 53
#define MOVESET_FORM_RAICHU_MEGA_Y    NATIONAL_DEX_COUNT + 54
#define MOVESET_FORM_MEWTWO_MEGA_X    NATIONAL_DEX_COUNT + 55
#define MOVESET_FORM_MEWTWO_MEGA_Y    NATIONAL_DEX_COUNT + 56
#define MOVESET_FORM_LATIOS_MEGA      NATIONAL_DEX_COUNT + 57

#define MOVESET_MAX MOVESET_FORM_LATIOS_MEGA

#define UNOWN_FORM_A     0
#define UNOWN_FORM_B     1
#define UNOWN_FORM_C     2
#define UNOWN_FORM_D     3
#define UNOWN_FORM_E     4
#define UNOWN_FORM_F     5
#define UNOWN_FORM_G     6
#define UNOWN_FORM_H     7
#define UNOWN_FORM_I     8
#define UNOWN_FORM_J     9
#define UNOWN_FORM_K     10
#define UNOWN_FORM_L     11
#define UNOWN_FORM_M     12
#define UNOWN_FORM_N     13
#define UNOWN_FORM_O     14
#define UNOWN_FORM_P     15
#define UNOWN_FORM_Q     16
#define UNOWN_FORM_R     17
#define UNOWN_FORM_S     18
#define UNOWN_FORM_T     19
#define UNOWN_FORM_U     20
#define UNOWN_FORM_V     21
#define UNOWN_FORM_W     22
#define UNOWN_FORM_X     23
#define UNOWN_FORM_Y     24
#define UNOWN_FORM_Z     25
#define UNOWN_FORM_EXC   26
#define UNOWN_FORM_QUE   27
#define UNOWN_FORM_COUNT 28

#define CASTFORM_FORM_NORMAL 0
#define CASTFORM_FORM_SUNNY  1
#define CASTFORM_FORM_RAINY  2
#define CASTFORM_FORM_SNOWY  3
#define CASTFORM_FORM_COUNT  4

#define DEOXYS_FORM_NORMAL  0
#define DEOXYS_FORM_ATTACK  1
#define DEOXYS_FORM_DEFENSE 2
#define DEOXYS_FORM_SPEED   3
#define DEOXYS_FORM_COUNT   4

#define BURMY_FORM_PLANT 0
#define BURMY_FORM_SAND  1
#define BURMY_FORM_TRASH 2
#define BURMY_FORM_COUNT 3

#define WORMADAM_FORM_PLANT 0
#define WORMADAM_FORM_SAND  1
#define WORMADAM_FORM_TRASH 2
#define WORMADAM_FORM_COUNT 3

#define CHERRIM_FORM_OVERCAST 0
#define CHERRIM_FORM_SUNSHINE 1
#define CHERRIM_FORM_COUNT    2

#define SHELLOS_FORM_WEST  0
#define SHELLOS_FORM_EAST  1
#define SHELLOS_FORM_COUNT 2

#define GASTRODON_FORM_WEST  0
#define GASTRODON_FORM_EAST  1
#define GASTRODON_FORM_COUNT 2

#define ROTOM_FORM_BASE  0
#define ROTOM_FORM_HEAT  1
#define ROTOM_FORM_WASH  2
#define ROTOM_FORM_FROST 3
#define ROTOM_FORM_FAN   4
#define ROTOM_FORM_MOW   5
#define ROTOM_FORM_COUNT 6

#define GIRATINA_FORM_ALTERED 0
#define GIRATINA_FORM_ORIGIN  1
#define GIRATINA_FORM_COUNT   2

#define SHAYMIN_FORM_LAND  0
#define SHAYMIN_FORM_SKY   1
#define SHAYMIN_FORM_COUNT 2

#define ARCEUS_FORM_COUNT 18

#define LUCARIO_FORM_BASE   0
#define LUCARIO_FORM_MEGA   1
#define LUCARIO_FORM_MEGA_Z 2
#define LUCARIO_FORM_COUNT  3

#define TYRANITAR_FORM_BASE  0
#define TYRANITAR_FORM_MEGA  1
#define TYRANITAR_FORM_COUNT 2

#define VENUSAUR_FORM_BASE  0
#define VENUSAUR_FORM_MEGA  1
#define VENUSAUR_FORM_COUNT 2

#define BLASTOISE_FORM_BASE  0
#define BLASTOISE_FORM_MEGA  1
#define BLASTOISE_FORM_COUNT 2

#define BEEDRILL_FORM_BASE  0
#define BEEDRILL_FORM_MEGA  1
#define BEEDRILL_FORM_COUNT 2

#define PIDGEOT_FORM_BASE  0
#define PIDGEOT_FORM_MEGA  1
#define PIDGEOT_FORM_COUNT 2

#define SLOWBRO_FORM_BASE  0
#define SLOWBRO_FORM_MEGA  1
#define SLOWBRO_FORM_COUNT 2

#define GENGAR_FORM_BASE  0
#define GENGAR_FORM_MEGA  1
#define GENGAR_FORM_COUNT 2

#define PINSIR_FORM_BASE  0
#define PINSIR_FORM_MEGA  1
#define PINSIR_FORM_COUNT 2

#define AMPHAROS_FORM_BASE  0
#define AMPHAROS_FORM_MEGA  1
#define AMPHAROS_FORM_COUNT 2

#define STEELIX_FORM_BASE  0
#define STEELIX_FORM_MEGA  1
#define STEELIX_FORM_COUNT 2

#define SCIZOR_FORM_BASE  0
#define SCIZOR_FORM_MEGA  1
#define SCIZOR_FORM_COUNT 2

#define HERACROSS_FORM_BASE  0
#define HERACROSS_FORM_MEGA  1
#define HERACROSS_FORM_COUNT 2

#define HOUNDOOM_FORM_BASE  0
#define HOUNDOOM_FORM_MEGA  1
#define HOUNDOOM_FORM_COUNT 2

#define SCEPTILE_FORM_BASE  0
#define SCEPTILE_FORM_MEGA  1
#define SCEPTILE_FORM_COUNT 2

#define BLAZIKEN_FORM_BASE  0
#define BLAZIKEN_FORM_MEGA  1
#define BLAZIKEN_FORM_COUNT 2

#define SWAMPERT_FORM_BASE  0
#define SWAMPERT_FORM_MEGA  1
#define SWAMPERT_FORM_COUNT 2

#define SABLEYE_FORM_BASE  0
#define SABLEYE_FORM_MEGA  1
#define SABLEYE_FORM_COUNT 2

#define MAWILE_FORM_BASE  0
#define MAWILE_FORM_MEGA  1
#define MAWILE_FORM_COUNT 2

#define AGGRON_FORM_BASE  0
#define AGGRON_FORM_MEGA  1
#define AGGRON_FORM_COUNT 2

#define MEDICHAM_FORM_BASE  0
#define MEDICHAM_FORM_MEGA  1
#define MEDICHAM_FORM_COUNT 2

#define MANECTRIC_FORM_BASE  0
#define MANECTRIC_FORM_MEGA  1
#define MANECTRIC_FORM_COUNT 2

#define BANETTE_FORM_BASE  0
#define BANETTE_FORM_MEGA  1
#define BANETTE_FORM_COUNT 2

#define ALAKAZAM_FORM_BASE  0
#define ALAKAZAM_FORM_MEGA  1
#define ALAKAZAM_FORM_COUNT 2

#define GYARADOS_FORM_BASE  0
#define GYARADOS_FORM_MEGA  1
#define GYARADOS_FORM_COUNT 2

#define ABSOL_FORM_BASE   0
#define ABSOL_FORM_MEGA   1
#define ABSOL_FORM_MEGA_Z 2
#define ABSOL_FORM_COUNT  3

#define GLALIE_FORM_BASE  0
#define GLALIE_FORM_MEGA  1
#define GLALIE_FORM_COUNT 2

#define SALAMENCE_FORM_BASE  0
#define SALAMENCE_FORM_MEGA  1
#define SALAMENCE_FORM_COUNT 2

#define LOPUNNY_FORM_BASE  0
#define LOPUNNY_FORM_MEGA  1
#define LOPUNNY_FORM_COUNT 2

#define GARCHOMP_FORM_BASE  0
#define GARCHOMP_FORM_MEGA  1
#define GARCHOMP_FORM_COUNT 2

#define ABOMASNOW_FORM_BASE  0
#define ABOMASNOW_FORM_MEGA  1
#define ABOMASNOW_FORM_COUNT 2

#define GALLADE_FORM_BASE  0
#define GALLADE_FORM_MEGA  1
#define GALLADE_FORM_COUNT 2

#define GARDEVOIR_FORM_BASE  0
#define GARDEVOIR_FORM_MEGA  1
#define GARDEVOIR_FORM_COUNT 2

#define ALTARIA_FORM_BASE  0
#define ALTARIA_FORM_MEGA  1
#define ALTARIA_FORM_COUNT 2

#define SHARPEDO_FORM_BASE  0
#define SHARPEDO_FORM_MEGA  1
#define SHARPEDO_FORM_COUNT 2

#define DRAGONITE_FORM_BASE  0
#define DRAGONITE_FORM_MEGA  1
#define DRAGONITE_FORM_COUNT 2

#define CLEFABLE_FORM_BASE  0
#define CLEFABLE_FORM_MEGA  1
#define CLEFABLE_FORM_COUNT 2

#define FROSLASS_FORM_BASE  0
#define FROSLASS_FORM_MEGA  1
#define FROSLASS_FORM_COUNT 2

#define EGG_FORM_BASE    0
#define EGG_FORM_MANAPHY 1
#define EGG_FORM_COUNT   2

#define CHARIZARD_FORM_BASE   0
#define CHARIZARD_FORM_MEGA_Y 1
#define CHARIZARD_FORM_COUNT  2

#define RAICHU_FORM_BASE   0
#define RAICHU_FORM_MEGA_Y 1
#define RAICHU_FORM_COUNT  2

#define MEWTWO_FORM_BASE   0
#define MEWTWO_FORM_MEGA_X 1
#define MEWTWO_FORM_MEGA_Y 2
#define MEWTWO_FORM_COUNT  3

#define LATIOS_FORM_BASE  0
#define LATIOS_FORM_MEGA  1
#define LATIOS_FORM_COUNT 2

#endif
