species_data_files += files('data.json', 'sprite_data.json')

species_data_files += files('forms/mega_x/data.json')

mewtwo_mega_x_icon = files('forms/mega_x/icon.png')

otherpoke_extra_sprites += files(
    'forms/base/back.png',
    'forms/base/front.png',
    'forms/mega_x/back.png',
    'forms/mega_x/front.png',
)

otherpoke_extra_palettes += files(
    'forms/base/normal.pal',
    'forms/base/shiny.pal',
    'forms/mega_x/normal.pal',
    'forms/mega_x/shiny.pal',
)

poke_icon_files += files('icon.png')

pokegra_files += files('male_back.png')
pokegra_files += files('male_front.png')

pokefoot_files += files('footprint.png')
