// Auto-generated by tools/generate_follower_table.py -- DO NOT EDIT
#ifndef POKEPLATINUM_FOLLOWER_MON_GFX_H
#define POKEPLATINUM_FOLLOWER_MON_GFX_H

#include <nitro.h>

u16 FollowerMon_GetGfxID(u16 species, u8 form, BOOL isFemale);

#endif // POKEPLATINUM_FOLLOWER_MON_GFX_H
