#ifndef POKEPLATINUM_CONSTANTS_BATTLE_TERRAIN_H
#define POKEPLATINUM_CONSTANTS_BATTLE_TERRAIN_H

#define TERRAIN_SPECIAL TERRAIN_AARON

#define TERRAIN_DURATION 5

#endif // POKEPLATINUM_CONSTANTS_BATTLE_TERRAIN_H
