species_data_files += files('data.json', 'sprite_data.json')

species_data_files += files('forms/mega/data.json')

clefable_mega_icon = files('forms/mega/icon.png')

otherpoke_extra_sprites += files(
    'forms/base/back.png',
    'forms/base/front.png',
    'forms/mega/back.png',
    'forms/mega/front.png',
)
otherpoke_extra_palettes += files(
    'forms/base/normal.pal',
    'forms/base/shiny.pal',
    'forms/mega/normal.pal',
    'forms/mega/shiny.pal',
)

poke_icon_files += files('icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

pokefoot_files += files('footprint.png')
